[package]
name = "jmaple"
version = "0.1.0"
edition = "2021"
description = "the red rust rewrite of cbonsai inspired by my dads japanese red maple tree"
license = "MIT"

[dependencies]
cursive = "0.20.0"
